### ISSUE TITLE
Flagged as beta on Wowace/Curse

### ISSUE THREAD

**Issue by Stanzilla** [Rainrider/LibArtifactData-1.0#13]
Hey there, your latest release on Curse is flagged as beta, so everyone on the release version will be stuck on the old 1.1 release from 2016. Might wanna change that since the old version is causing a lot of problems.

**Comment by Rainrider** [comment]
It is beta as in beta quality. This is a lib, the add-on that uses it should embed the right version.

**Comment by Stanzilla** [comment]
Your library is used by tons of WeakAuras and those people have the lib installed standalone.
