### ISSUE TITLE
C_ArtifactUI.GetCostForPointAtRank(rank, tier)

### ISSUE THREAD

**Issue by KrazyTurk** [Rainrider/LibArtifactData-1.0#14]
Whenever I log in, I get this coming up
Running on the 1.2 Beta

1x FrameXML\MainMenuBar.lua:125: Usage: local cost = C_ArtifactUI.GetCostForPointAtRank(rank, tier)
[C]:: in function 'GetCostForPointAtRank'
FrameXML\MainMenuBar.lua:125: in function <FrameXML\MainMenuBar.lua:123>
...lUI\Libs\LibArtifactData-1.0\LibArtifactData-1.0-11.lua:232: in function <...lUI\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:223>
...lUI\Libs\LibArtifactData-1.0\LibArtifactData-1.0-11.lua:247: in function <...lUI\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:243>
...lUI\Libs\LibArtifactData-1.0\LibArtifactData-1.0-11.lua:310: in function '?'
...lUI\Libs\LibArtifactData-1.0\LibArtifactData-1.0-11.lua:68: in function <...lUI\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:68>

Locals:
(*temporary) = 37
(*temporary) = nil

Not sure how to print out a nice list of addons w/ versions like others have done :( here is a list of what I have

!Aurora_RealUI
ACP
AffDots
AngryAssignments
AskMrRobot
Auctionator
Aurora
BadBoy
BadBoy_
CCleaner
BadBoy_Guilded
BagBrother
Bagnon
Bagnon_Scrap
BagSync
Bartender4
Bugger
!BugGrabber
Clique
Eaglerror
eAlign
EasyMail
epgp_lootmaster
epgp_lootmaster_ml
Foglight
FreebTip
FreebTipiLvl
FreebTipSpec
GemChipHelper
Grid2
Grid2RaidDebuffs
Grid2LDB
HandyNotes
HandyNotes_DraenorTreasures
HandyNotes_Legion
RaresTreasures
Kui_Nameplates
Kui_Nameplates_Core_Config
Kui_Nameplates_Core
Masque
MasterPlanA
MikScrollingBattleText
nibRealUI
nibRealUI_BossSkins
nibRealUI_Init
OmniCC
EODSkin
Fireskin
ShadowSkin
SkullSkin
OttoSkin
Prat-3.0
Prat-3.0_Libraries
QuickTalents
IskarAssist
Raven
Scrap
Scrap_
Spotlight
ServerHop
SharedMedia
Skada
SlashCombatLog
SubSpec
TalentProfile
ThogarAssist
TidyPlates
TidyPlatesHub
TidyPlatesWidgets
TidyPlates_Graphite
TidyPlates_Grey
TidyPlates_Neon
TidyPlates_Quatre
WeakAuras
WIM
WIM_Elvui
WorldQuestGroupFinder
WorldQuestsList
TradeSkillMaster
TradeSkillMaster_Accounting
TradeSkillMaster_AppHelper
TradeSkillMaster_AuctionDB
TradeSkillMaster_Auctioning
TradeSkillMaster_Crafting
TradeSkillMaster_Destroying
TradeSkillMaster_Mailing
TradeSkillMaster_Shopping
TradeSkillMaster_Vendoring
TradeSkillMaster_Warehousing
DBM-Core
DBM-DefaultSkin
DBM-StatusBarTimers

**Comment by Mikeprod** [comment]
A future update will definitly fix all the errors.

**Comment by Mikeprod** [comment]
You are probably not on the last version of the lib. Aka 15

**Comment by KrazyTurk** [comment]
1.2 was the latest I found on Curse flagged as beta

**Comment by Mikeprod** [comment]
Curse is not up to date, replace the library you got with the github version.

**Comment by Rainrider** [comment]
[1.2-Beta](https://www.wowace.com/projects/libartifactdata-1-0/files/2398448) is the latest release on curse and it is the right one. It has other issues though, but I'll need some time to fix them.
