### ISSUE TITLE
received this error thought I would pass it along

### ISSUE THREAD

**Issue by inthemoneybusiness** [Rainrider/LibArtifactData-1.0#15]
5x ...ale\libs\LibArtifactData-1.0\LibArtifactData-1.0-15.lua:166: attempt to get length of local 'powers' (a nil value)
...ale\libs\LibArtifactData-1.0\LibArtifactData-1.0-15.lua:166: in function <...ale\libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:162>
...ale\libs\LibArtifactData-1.0\LibArtifactData-1.0-15.lua:379: in function `?'
...ale\libs\LibArtifactData-1.0\LibArtifactData-1.0-15.lua:68: in function <...ale\libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:68>

Locals:
artifactID = 128862
traits = <table> {
}
powers = nil
(*temporary) = 1
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to get length of local 'powers' (a nil value)"
GetPowers = <function> defined =[C]:-1
GetPowerInfo = <function> defined =[C]:-1
GetSpellInfo = <function> defined =[C]:-1
artifacts = <table> {
 knowledgeLevel = 27
 knowledgeMultiplier = 1301
 127857 = <table> {
 }
 128862 = <table> {
 }
 128820 = <table> {
 }
}

**Comment by Rainrider** [comment]
The addon you are using has embedded an old version of LAD. The current minor is 16, not 15
