### ISSUE TITLE
addon draining memory

### ISSUE THREAD

**Issue by jekoder** [Rainrider/LibArtifactData-1.0#18]
[https://cdn.discordapp.com/attachments/218084462523711489/404112379643953172/unknown.png](https://cdn.discordapp.com/attachments/218084462523711489/404112379643953172/unknown.png)

artifact data keeps draining memory when enabled

**Comment by Rainrider** [comment]
![lad dh](https://user-images.githubusercontent.com/363876/35183250-10a4fc74-fde3-11e7-9df5-d6a374ccb7be.jpg) - on a Demon Hunter
![lad hunter](https://user-images.githubusercontent.com/363876/35183251-13ebf36a-fde3-11e7-8f90-c774c440f15c.jpg) - on a Hunter
![lad monk](https://user-images.githubusercontent.com/363876/35183256-1dbb458a-fde3-11e7-8f32-302a38aca050.jpg)  - on a Monk

[GetAddOnMemoryUsage](http://wowprogramming.com/docs/api/GetAddOnMemoryUsage)

**Comment by jekoder** [comment]
https://cdn.discordapp.com/attachments/388998464144539650/404606047446237186/unknown.png
this is on my dk, but i think a it's my deathstrike weakaura causing the problem

[image](https://user-images.githubusercontent.com/1997539/35193989-6b8a6cce-feff-11e7-8338-c6b24f88ff4b.png)

**Comment by Rainrider** [comment]
Could you run `/dump LibStub('LibArtifactData-1.0')` in-game and post a screenshot of it here? It should look like this:
![wowscrnshot_012118_141721](https://user-images.githubusercontent.com/363876/35194612-5129bd24-feb6-11e7-8f9e-c1d1774a1d7d.jpg)
I think someone is storing their stuff on the LAD object.

**Comment by jekoder** [comment]
![alt text](https://cdn.discordapp.com/attachments/388998464144539650/404661334400303104/unknown.png)

**Comment by Rainrider** [comment]
TBH, I don't know what might be causing it then, it shouldn't exceed 150-200 KB in memory use. Sadly I cannot solve this as long as I cannot reproduce your reported case.

**Comment by Rainrider** [comment]
It would be nice if you could help me narrow it down. A list of addons you have installed that use LAD would be helpful. You could use a tool like [grepWin](https://sourceforge.net/projects/grepwin/files/) to search for those.
![grepwin lad](https://user-images.githubusercontent.com/363876/35245340-7d28f242-ffc3-11e7-92af-99399100fa72.png)
Use `*.toc` as a file names match like in the screenshot.

Also any WeakAuras scripts that use LAD would be interesting.

Apart from that, some steps to reproduce are needed. Is the memory consumption that high right after you login or does it take some time? Do I have to do something special to reproduce it (join a raid, login on a certain class, wait for X minutes with addon XYZ installed)?

**Comment by jekoder** [comment]
so currently a easy way to reproduce it is to 
1.    Log in a 110 death knight switch specialisation to blood and use https://wago.io/NkaTBpcPW this death strike weakaura
 with lib enabled.

2.    use elvui's system datatext to track memory usage.
then you should see the memory usage rise very rapidly about 2mb/s

and u don't to be in party or raid

the memory issue also happens to the https://wago.io/NkogH0_D- which is from same author
i also contact the author of weakaura but haven't heard anything back yet

**Comment by jekoder** [comment]
![alt text](https://user-images.githubusercontent.com/1997539/35252949-e8b0f186-0036-11e8-8ab7-95bf08c2f0e3.png)

**Comment by Rainrider** [comment]
Could you tell the WA guy to use [`:IterateTraits`](https://github.com/Rainrider/LibArtifactData-1.0/wiki/API#iteratetraitsartifactid) instead of `:GetArtifactTraits` and see if this helps with the problem?

The reason is s/he calls `:GetArtifactTraits` on every frame instead of using CallbackHandler to pull it only when changes occur. `:GetArtifactTraits` returns a reference to a copy of the traits table rather than providing direct access to the data, thus the memory consumption is blamed on LAD. ~~I should have done it by using a read-only table instead~~.

I won't have time for this today, ~~but I'll make some changes to LAD to alleviate this behavior.~~ Can't be done in Lua 5.1, using the iterator is the only solution for now.

**Comment by jekoder** [comment]
I forward this to the author and also changed code myself, this does solve memory consumption problem, now LAB is only using 154kb

**Comment by Rainrider** [comment]
You might not want to see the CPU load of this script btw. The author basically ignored everything that's good practice.
