### ISSUE TITLE
8.0 | Attempt to unregister unknown event "ARTIFACT_MAX_RANKS_UPDATE"

### ISSUE THREAD

**Issue by tordenflesk** [Rainrider/LibArtifactData-1.0#21]
141x ...ras\libs\LibArtifactData-1.0\LibArtifactData-1.0-21.lua:510: Attempt to unregister unknown event "ARTIFACT_MAX_RANKS_UPDATE"
[C]: in function `UnregisterEvent'
...ras\libs\LibArtifactData-1.0\LibArtifactData-1.0-21.lua:510: in function <...ras\libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:502>
...ras\libs\LibArtifactData-1.0\LibArtifactData-1.0-21.lua:723: in function <...ras\libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:721>
...ras\libs\LibArtifactData-1.0\LibArtifactData-1.0-21.lua:802: in function `?'
...ras\libs\LibArtifactData-1.0\LibArtifactData-1.0-21.lua:486: in function <...ras\libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:486>

Locals:
(*temporary) = ArtifactFrame {
 0 = <userdata>
 RefreshKnowledgeRanks = <function> defined @Blizzard_ArtifactUI\Blizzard_ArtifactUI.lua:223
 EvaulateForgeState = <function> defined @Blizzard_ArtifactUI\Blizzard_ArtifactUI.lua:154
 numTabs = 2
 CloseButton = <unnamed> {
 }
 OnKnowledgeLeave = <function> defined @Blizzard_ArtifactUI\Blizzard_ArtifactUI.lua:254
 AppearancesTab = <unnamed> {
 }
 PerksTab = <unnamed> {
 }
 OnKnowledgeEnter = <function> defined @Blizzard_ArtifactUI\Blizzard_ArtifactUI.lua:240
 Background = <unnamed> {
 }
 BorderFrame = <unnamed> {
 }
 OnInventoryItemMouseLeave = <function> defined @Blizzard_ArtifactUI\Blizzard_ArtifactUI.lua:272
 AppearanceTabHelpBox = <unnamed> {
 }
 OnAppearanceChanging = <function> defined @Blizzard_ArtifactUI\Blizzard_ArtifactUI.lua:133
 OnShow = <function> defined @Blizzard_ArtifactUI\Blizzard_ArtifactUI.lua:69
 OnLoad = <function> defined @Blizzard_ArtifactUI\Blizzard_ArtifactUI.lua:60
 OnHide = <function> defined @Blizzard_ArtifactUI\Blizzard_ArtifactUI.lua:88
 PerksTabButton = ArtifactFrameTab1 {
 }
 KnowledgeLevelHelpBox = <unnamed> {
 }
 OnEvent = <function> defined @Blizzard_ArtifactUI\Blizzard_ArtifactUI.lua:101
 SetupPerArtifactData = <function> defined @Blizzard_ArtifactUI\Blizzard_ArtifactUI.lua:199
 VisitForgeOverlay = <unnamed> {
 }
 ForgeLevelFrame = <unnamed> {
 }
 ForgeBadgeFrame = <unnamed> {
 }
 OnTraitsRefunded = <function> defined @Blizzard_ArtifactUI\Blizzard_ArtifactUI.lua:129
 OnInventoryItemMouseEnter = <function> defined @Blizzard_ArtifactUI\Blizzard_ArtifactUI.lua:259
 AppearancesTabButton = ArtifactFrameTab2 {
 }
 SetTab = <function> defined @Blizzard_ArtifactUI\Blizzard_ArtifactUI.lua:179
}
(*temporary) = "ARTIFACT_MAX_RANKS_UPDATE"

**Comment by Rainrider** [comment]
Fixed by 0955f82e832903b46c397274af0427aec5c43fb7
