### ISSUE TITLE
GetAcquiredArtifactPower loops one too many times

### ISSUE THREAD

**Issue by Silarn** [Rainrider/LibArtifactData-1.0#5]
I wrote a tiny addon to give myself a feed of each artifact's acquired power and the combined total.

It seemed a bit too high, and I soon confirmed it when it showed 100k before it should have.

Either numRanksPurchased is one too high or the while loops are running one too many times. If you change it to simply rank < data.numRanksPurchased, the total power comes out correct.

An easy way to see this in action is to watch the total as you drop a new point onto the weapon - the totals jump up significantly because it's adding the additional XP from the next Artifact level to the total.

**Comment by Rainrider** [comment]
You are right! There is a hidden achievement you could use to compare the values LAD returns. Use `/dump (select(4,GetAchievementCriteriaInfo(11158,1)))`. However, after applying your proposed fix, LAD returns 125 more than the above command on one character, and exactly the same on another. This is strange

**Comment by Silarn** [comment]
Odd. Not sure about that discrepancy. I can try on a couple chars to see how it compares for me.
