### ISSUE TITLE
PvP Skin causing Blizzard's artifact UI to bug in conjection with GetArtifactInfo().

### ISSUE THREAD

**Issue by Hekili** [Rainrider/LibArtifactData-1.0#7]
Running LibArtifactData-1.0:GetArtifactInfo() is leading to this error in the Blizzard ArtifactPerks UI (it repeats itself), apparently when the "kill 1000 players" skin is equipped.

Message: ...ddOns\Blizzard_ArtifactUI\Blizzard_ArtifactPerks.lua:24: Usage: GetAppearanceInfoByID(artifactAppearanceID)
Time: 10/05/16 14:40:45
Count: 325
Stack: [C]: ?
[C]: in function GetAppearanceInfoByID'
...ddOns\Blizzard_ArtifactUI\Blizzard_ArtifactPerks.lua:24: in functionRefreshModel'
...ddOns\Blizzard_ArtifactUI\Blizzard_ArtifactPerks.lua:180: in function `TryRefresh'
...ddOns\Blizzard_ArtifactUI\Blizzard_ArtifactPerks.lua:81: in function <...ddOns\Blizzard_ArtifactUI\Blizzard_ArtifactPerks.lua:80>

Changing to a different artifact skin will cause the error to cease.  I can't get deeper debug information from there.

**Comment by Rainrider** [comment]
I don't see how this could relate to LAD. `LAD:GetArtifactInfo()` does not invoke any calls to the API, it just returns a copy of internal data.
