### ISSUE TITLE
Lua error when loading

### ISSUE THREAD

**Issue by JJ-D** [Rainrider/LibArtifactData-1.0#8]
I'm using LibArtifactData in an addon called EventHorizon that I use for my shadow priest. I recently started getting an error every time I logged in: 

Message: ...izon\lib\LibArtifactData-1.0\LibArtifactData-1.0.lua:196: 'for' limit must be a number
Time: 10/27/16 20:08:05
Count: 3
Stack: [C]: ?
...izon\lib\LibArtifactData-1.0\LibArtifactData-1.0.lua:196: in function <...izon\lib\LibArtifactData-1.0\LibArtifactData-1.0.lua:194>
...izon\lib\LibArtifactData-1.0\LibArtifactData-1.0.lua:330: in function `?'
...izon\lib\LibArtifactData-1.0\LibArtifactData-1.0.lua:68: in function <...izon\lib\LibArtifactData-1.0\LibArtifactData-1.0.lua:68>

At the suggestion of the addon author I disabled all my addons and only loaded EventHorizon, and I got no errors. Then I was able to narrow it down to a conflict with the TradeSkillMaster core addon. When I had just those 2 addons enabled, I get the error. If I only have Tradeskillmaster enabled, no error.  
So the problem only presents when I have those 2 addons loaded at the same time. 

Thanks

**Comment by Rainrider** [comment]
The version of LAD embedded in EventHorizon is old. You can bug the author to either embed the last version or add LAD under the OptDeps field in his ToC file. If he does the latter you could just install LAD as a stand-alone addon and see if the issue is gone.

**Comment by JJ-D** [comment]
Thanks. I went in and manually updated the embedded LAD lua files and it did resolve the issue.

**Comment by Rainrider** [comment]
This is not a good solution. The next time you update EventHorizon it will
overwrite your changes.

**Comment by JJ-D** [comment]
I know, I also reached out to the EHZ developer and gave them your response about updating the embedded LAD.
